namespace Capsule.Attribution;

/// <summary>
/// Expose a method or property on the capsule interface. If the capsule interface is not generated by Capsule
/// Generator, you are responsible that the interface matches the exposed methods/properties.
///
/// The synchronization mode can be customized by specifying the <see cref="Synchronization"/> property, which defaults
/// to "await completion and return result".
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Event)]
public sealed class ExposeAttribute : Attribute
{
    public CapsuleSynchronization Synchronization { get; init; } = CapsuleSynchronization.AwaitCompletion;
}
