site_name: Capsule

repo_url: https://github.com/thedmi/capsule

theme:
  name: material
  palette:
    primary: deep purple
    accent: green
  icon:
    repo: fontawesome/brands/github
    logo: material/rocket
    
  features:
    - navigation.instant
    
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg