site_name: Capsule

repo_url: https://github.com/thedmi/capsule

theme:
  name: material
  palette:
    primary: deep purple
    accent: green
  icon:
    repo: fontawesome/brands/github
    
  features:
    - navigation.instant
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
